- name: create ansible group
  user:
    name: ansible

- name: create ansible user
  user:
    name: ansible
    group: ansible

- name: add ssh key for ansible
  authorized_key:
    user: ansible
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPwxLiN165NHLkJ6VH/aDhFOwpSoWMKGE0VTHa0DfXC5 ansible"

- name: add sudoers file for ansible
  copy:
    src: sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440
